### ISSUE TITLE
Missing import statement

### ISSUE THREAD

**Issue by rodrigogramitto** [pirates-of-the-query-bbean/atelier#40]
https://github.com/pirates-of-the-query-bbean/atelier/blob/7c8bfd89c43418a1ee37ed00e26c774585aa9c09/client/src/widgets/Questions/QuestionList.jsx#L1-L27

I see this API call is commented out, however consider importing axios module for API calls inside component.

**Comment by malloryporche** [comment]
Removed API call, closing out this issue.
